# artifact project settings

# Note: {cwd} == current directory of THIS file
#       {repo} == directory of the `.art` file

# directories containing artifact toml files
artifact_paths = ["{repo}/design"]

# artifact paths to exclude. This is how you can avoid trying
# to load .git/.hg/etc directories (or anything else you don't
# want to include
exclude_artifact_paths = ["{repo}/.git", "{repo}/deps", "{repo}/_build"]

# directories containing code that has artifact links
code_paths = ["{repo}/lib", "{repo}/spec"]

# directories to exclude when searching through code
exclude_code_paths = []
